"use client";

import { useCallback, useEffect, useState } from "react";
import { Clock3, PackageCheck, Phone, UserRound, WalletCards, X } from "lucide-react";

type Item={id:number;name:string;qty:number;note?:string;status:string};
type Order={id:number;orderNumber:string;queueNumber:string;customerName?:string;customerPhone?:string;status:string;paymentStatus:string;total:number;createdAt:string;items:Item[]};
const statusText:Record<string,string>={SENT:"รอครัวรับ",PREPARING:"กำลังทำ",READY:"พร้อมรับ",SERVED:"รับแล้ว",CANCELLED:"ยกเลิก"};
const statusClass:Record<string,string>={SENT:"bg-gray-100 text-gray-600",PREPARING:"bg-amber-100 text-amber-700",READY:"bg-emerald-100 text-emerald-700"};

export default function TakeawayPage(){
  const [orders,setOrders]=useState<Order[]>([]);const [message,setMessage]=useState("");const [loadingId,setLoadingId]=useState<number|null>(null);
  const load=useCallback(()=>fetch("/api/orders?view=takeaway").then(r=>r.json()).then(setOrders),[]);
  useEffect(()=>{load();const timer=setInterval(load,10000);return()=>clearInterval(timer);},[load]);
  async function action(orderId:number,action:string,method?:string){setLoadingId(orderId);setMessage("");const r=await fetch("/api/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId,action,method})});const d=await r.json();setLoadingId(null);if(!r.ok)return setMessage(d.error);setMessage(action==="pay"?"รับชำระเงินแล้ว":action==="pickup"?"ส่งมอบอาหารเรียบร้อยแล้ว":"ยกเลิกออเดอร์และคืนสต็อกแล้ว");load();}
  async function cancel(order:Order){if(!confirm(`ยืนยันยกเลิกคิว ${order.queueNumber}?`))return;action(order.id,"cancel");}
  return <div className="p-6 overflow-y-auto"><div className="flex flex-wrap justify-between items-center gap-3 mb-5"><div><p className="text-sm text-gray-400">ติดตามตั้งแต่ส่งเข้าครัวจนลูกค้ารับอาหาร</p><p className="text-sm font-medium mt-1">คิวที่กำลังดำเนินการ {orders.length} คิว</p></div><button onClick={load} className="bg-white px-4 py-2 rounded-xl text-sm">รีเฟรช</button></div>{message&&<p className={`mb-4 text-sm ${message.includes("แล้ว")?"text-emerald-600":"text-red-500"}`}>{message}</p>}
  <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{orders.map(order=><article key={order.id} className={`bg-white rounded-2xl border overflow-hidden ${order.status==="READY"?"border-emerald-300 shadow-sm":"border-gray-100"}`}><header className={`p-4 flex justify-between ${order.status==="READY"?"bg-emerald-600 text-white":"bg-[#212A3A] text-white"}`}><div><p className="text-2xl font-bold">{order.queueNumber}</p><p className="text-xs opacity-70">{order.orderNumber}</p></div><span className={`h-fit px-3 py-1 rounded-full text-xs ${order.status==="READY"?"bg-white text-emerald-700":statusClass[order.status]}`}>{statusText[order.status]}</span></header><div className="p-4"><div className="grid grid-cols-2 gap-2 text-xs text-gray-500"><span className="flex items-center gap-1"><UserRound size={14}/>{order.customerName||"ไม่ระบุชื่อ"}</span><span className="flex items-center gap-1"><Phone size={14}/>{order.customerPhone||"ไม่ระบุเบอร์"}</span><span className="flex items-center gap-1"><Clock3 size={14}/>สั่งเมื่อ {new Date(order.createdAt).toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit"})}</span><span className={`font-medium ${order.paymentStatus==="PAID"?"text-emerald-600":"text-red-500"}`}>{order.paymentStatus==="PAID"?"ชำระแล้ว":"ยังไม่ชำระ"}</span></div><div className="my-4 border-y border-gray-100 py-3 space-y-2">{order.items.map(item=><div key={item.id} className="flex justify-between text-sm"><span><b className="text-blue-600 mr-2">{item.qty}×</b>{item.name}{item.note&&<small className="block ml-6 text-red-500">{item.note}</small>}</span></div>)}</div><div className="flex justify-between font-semibold"><span>ยอดรวม</span><span className="text-blue-600">฿{order.total.toFixed(2)}</span></div>
  {order.paymentStatus==="UNPAID"?<div className="grid grid-cols-3 gap-2 mt-4"><button disabled={loadingId===order.id} onClick={()=>action(order.id,"pay","CASH")} className="bg-emerald-600 text-white py-2 rounded-lg text-xs">เงินสด</button><button disabled={loadingId===order.id} onClick={()=>action(order.id,"pay","PROMPTPAY")} className="bg-blue-600 text-white py-2 rounded-lg text-xs">พร้อมเพย์</button><button disabled={loadingId===order.id} onClick={()=>action(order.id,"pay","CARD")} className="bg-gray-700 text-white py-2 rounded-lg text-xs">บัตร</button></div>:<div className="mt-4 flex items-center gap-2 text-emerald-600 text-sm"><WalletCards size={16}/> รับชำระเงินแล้ว</div>}
  <div className="grid grid-cols-[1fr_auto] gap-2 mt-3"><button disabled={order.status!=="READY"||order.paymentStatus!=="PAID"||loadingId===order.id} onClick={()=>action(order.id,"pickup")} className="bg-[#356DDB] text-white rounded-xl py-2.5 disabled:bg-gray-200 disabled:text-gray-400 flex items-center justify-center gap-2 text-sm"><PackageCheck size={17}/> ลูกค้ารับอาหารแล้ว</button>{order.paymentStatus!=="PAID"&&<button onClick={()=>cancel(order)} className="px-3 rounded-xl bg-red-50 text-red-500"><X size={18}/></button>}</div></div></article>)}</div>
  {!orders.length&&<div className="text-center mt-24 text-gray-400"><PackageCheck size={52} className="mx-auto opacity-25 mb-3"/><p>ไม่มีคิวซื้อกลับบ้านที่กำลังดำเนินการ</p></div>}</div>;
}
