"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, PackageOpen, Plus, Save, Trash2 } from "lucide-react";

type Movement = { id:number; type:string; quantity:number; note?:string; createdAt:string };
type Ingredient = { id:number; name:string; unit:string; stock:number; minStock:number; costPerUnit:number; _count:{recipes:number}; movements:Movement[] };
type Recipe = { ingredientId:number; quantity:number; ingredient:Ingredient };
type Menu = { id:number; name:string; saleUnit:string; category:{name:string}; recipes:Recipe[] };

export default function InventoryPage(){
  const [ingredients,setIngredients]=useState<Ingredient[]>([]);const [menu,setMenu]=useState<Menu[]>([]);
  const [form,setForm]=useState({name:"",unit:"กรัม",stock:"",minStock:"",costPerUnit:""});
  const [receive,setReceive]=useState<Record<number,string>>({});const [selectedMenu,setSelectedMenu]=useState("");
  const [quantities,setQuantities]=useState<Record<number,string>>({});const [message,setMessage]=useState("");
  const load=useCallback(()=>Promise.all([fetch("/api/inventory").then(r=>r.json()),fetch("/api/recipes").then(r=>r.json())]).then(([i,m])=>{setIngredients(i);setMenu(m);}),[]);
  useEffect(()=>{load();},[load]);
  const selected=useMemo(()=>menu.find(m=>m.id===Number(selectedMenu)),[menu,selectedMenu]);
  useEffect(()=>{const next:Record<number,string>={};selected?.recipes.forEach(r=>next[r.ingredientId]=String(r.quantity));setQuantities(next);},[selected]);

  async function add(e:FormEvent){e.preventDefault();setMessage("");const r=await fetch("/api/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)return setMessage(d.error);setForm({name:"",unit:"กรัม",stock:"",minStock:"",costPerUnit:""});setMessage("เพิ่มวัตถุดิบแล้ว");load();}
  async function stockIn(id:number){const quantity=Number(receive[id]);if(!(quantity>0))return;const r=await fetch("/api/inventory",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"stock-in",id,quantity})});if(r.ok){setReceive({...receive,[id]:""});setMessage("รับวัตถุดิบเข้าสต็อกแล้ว");load();}}
  async function remove(id:number){if(!confirm("ลบวัตถุดิบนี้ใช่หรือไม่?"))return;const r=await fetch("/api/inventory",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)setMessage(d.error);else load();}
  async function saveRecipe(){if(!selectedMenu)return;const list=Object.entries(quantities).filter(([,q])=>Number(q)>0).map(([ingredientId,quantity])=>({ingredientId:Number(ingredientId),quantity:Number(quantity)}));const r=await fetch("/api/recipes",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({menuItemId:Number(selectedMenu),ingredients:list})});const d=await r.json();if(!r.ok)return setMessage(d.error);setMessage("บันทึกสูตรอาหารแล้ว");load();}

  return <div className="p-6 space-y-6 overflow-y-auto">
    <form onSubmit={add} className="bg-white rounded-2xl border border-gray-100 p-5"><h2 className="font-semibold mb-4">เพิ่มวัตถุดิบ</h2><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="ชื่อวัตถุดิบ" className="border rounded-xl px-3 py-2.5"/><input required value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} placeholder="หน่วย เช่น กรัม" className="border rounded-xl px-3 py-2.5"/><input type="number" min="0" step="0.01" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})} placeholder="ยอดตั้งต้น" className="border rounded-xl px-3 py-2.5"/><input type="number" min="0" step="0.01" value={form.minStock} onChange={e=>setForm({...form,minStock:e.target.value})} placeholder="จุดแจ้งเตือน" className="border rounded-xl px-3 py-2.5"/><button className="bg-[#356DDB] text-white rounded-xl px-4 py-2.5 flex items-center justify-center gap-2"><Plus size={17}/> เพิ่ม</button></div></form>
    {message&&<p className={`text-sm ${message.includes("แล้ว")?"text-emerald-600":"text-red-500"}`}>{message}</p>}
    <section><div className="flex justify-between mb-3"><h2 className="font-semibold">คงเหลือในสต็อก</h2><span className="text-sm text-gray-400">{ingredients.filter(i=>i.stock<=i.minStock).length} รายการใกล้หมด</span></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{ingredients.map(item=>{const low=item.stock<=item.minStock;return <div key={item.id} className={`bg-white rounded-2xl border p-5 ${low?"border-amber-300":"border-gray-100"}`}><div className="flex items-start justify-between"><div className={`w-11 h-11 rounded-xl grid place-items-center ${low?"bg-amber-50 text-amber-600":"bg-blue-50 text-blue-600"}`}>{low?<AlertTriangle size={21}/>:<PackageOpen size={21}/>}</div><button onClick={()=>remove(item.id)} className="text-gray-300 hover:text-red-500"><Trash2 size={17}/></button></div><h3 className="font-semibold mt-3">{item.name}</h3><div className="flex items-end gap-1 mt-1"><span className={`text-2xl font-semibold ${low?"text-amber-600":"text-gray-800"}`}>{item.stock.toLocaleString()}</span><span className="text-sm text-gray-400 mb-1">{item.unit}</span></div><p className="text-xs text-gray-400">แจ้งเตือนเมื่อ ≤ {item.minStock} · ใช้ใน {item._count.recipes} สูตร</p><div className="flex gap-2 mt-4"><input type="number" min="0" step="0.01" value={receive[item.id]||""} onChange={e=>setReceive({...receive,[item.id]:e.target.value})} placeholder="จำนวนรับเข้า" className="min-w-0 flex-1 border rounded-lg px-3 py-2 text-sm"/><button onClick={()=>stockIn(item.id)} className="bg-emerald-600 text-white rounded-lg px-3 text-sm">รับเข้า</button></div></div>})}</div></section>
    <section className="bg-white rounded-2xl border border-gray-100 p-5"><h2 className="font-semibold">กำหนดสูตรอาหาร</h2><p className="text-sm text-gray-400 mt-1">ระบุปริมาณวัตถุดิบที่ใช้ต่อเมนู 1 {selected?.saleUnit || "หน่วยขาย"}</p><select value={selectedMenu} onChange={e=>setSelectedMenu(e.target.value)} className="mt-4 w-full sm:max-w-md border rounded-xl px-4 py-3 bg-white"><option value="">เลือกเมนูอาหาร</option>{menu.map(m=><option key={m.id} value={m.id}>{m.name} · {m.category.name}</option>)}</select>{selected&&<div className="mt-5 grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{ingredients.map(i=><label key={i.id} className="border border-gray-100 rounded-xl p-3"><span className="text-sm font-medium">{i.name}</span><div className="flex items-center gap-2 mt-2"><input type="number" min="0" step="0.01" value={quantities[i.id]||""} onChange={e=>setQuantities({...quantities,[i.id]:e.target.value})} placeholder="0" className="w-full bg-gray-50 rounded-lg px-3 py-2"/><span className="text-xs text-gray-400">{i.unit}</span></div></label>)}</div>}{selected&&<button onClick={saveRecipe} className="mt-4 bg-[#212A3A] text-white rounded-xl px-5 py-2.5 flex items-center gap-2"><Save size={17}/> บันทึกสูตร</button>}</section>
  </div>;
}
