"use client";

import { useCallback, useEffect, useState } from "react";
import { Banknote, ClipboardList, Percent, ReceiptText } from "lucide-react";

type Report={summary:{sales:number;discounts:number;orders:number;average:number};topItems:Array<{name:string;qty:number;sales:number}>;payments:Array<{method:string;amount:number}>;daily:Array<{date:string;amount:number}>;recent:Array<{id:number;orderNumber:string;table:string;total:number;method:string;paidAt:string}>};
const empty:Report={summary:{sales:0,discounts:0,orders:0,average:0},topItems:[],payments:[],daily:[],recent:[]};
const methodText:Record<string,string>={CASH:"เงินสด",PROMPTPAY:"พร้อมเพย์",CARD:"บัตร"};
function localDate(date:Date){const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,10);}

export default function ReportsPage(){
  const now=new Date();const [from,setFrom]=useState(localDate(new Date(now.getFullYear(),now.getMonth(),1)));const [to,setTo]=useState(localDate(now));const [report,setReport]=useState<Report>(empty);
  const load=useCallback(()=>fetch(`/api/reports?from=${from}&to=${to}`).then(r=>r.json()).then(setReport),[from,to]);useEffect(()=>{load();},[load]);
  const cards=[{label:"ยอดขาย",value:`฿${report.summary.sales.toLocaleString(undefined,{minimumFractionDigits:2})}`,icon:Banknote,color:"text-emerald-600 bg-emerald-50"},{label:"จำนวนบิล",value:report.summary.orders,icon:ReceiptText,color:"text-blue-600 bg-blue-50"},{label:"ยอดเฉลี่ยต่อบิล",value:`฿${report.summary.average.toFixed(2)}`,icon:ClipboardList,color:"text-violet-600 bg-violet-50"},{label:"ส่วนลดรวม",value:`฿${report.summary.discounts.toFixed(2)}`,icon:Percent,color:"text-amber-600 bg-amber-50"}];
  const max=Math.max(...report.daily.map(d=>d.amount),1);
  return <div className="p-6 space-y-5 overflow-y-auto"><div className="bg-white rounded-2xl p-4 flex flex-wrap gap-3 items-end"><label className="text-sm text-gray-500">จาก<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="block mt-1 border rounded-xl px-3 py-2 text-gray-800"/></label><label className="text-sm text-gray-500">ถึง<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="block mt-1 border rounded-xl px-3 py-2 text-gray-800"/></label><button onClick={load} className="bg-[#356DDB] text-white px-5 py-2.5 rounded-xl">แสดงรายงาน</button></div>
  <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{cards.map(({label,value,icon:Icon,color})=><div key={label} className="bg-white rounded-2xl p-5 border border-gray-100 flex gap-4"><div className={`w-11 h-11 rounded-xl grid place-items-center ${color}`}><Icon size={21}/></div><div><p className="text-sm text-gray-400">{label}</p><p className="text-xl font-semibold">{value}</p></div></div>)}</div>
  <div className="grid lg:grid-cols-2 gap-5"><section className="bg-white rounded-2xl border border-gray-100 p-5"><h2 className="font-semibold">ยอดขายรายวัน</h2><div className="h-52 flex items-end gap-2 mt-5 border-b border-gray-100">{report.daily.map(day=><div key={day.date} className="flex-1 min-w-8 h-full flex flex-col justify-end items-center group"><span className="text-[10px] text-gray-400 mb-1 opacity-0 group-hover:opacity-100">฿{day.amount.toFixed(0)}</span><div className="w-full max-w-12 bg-blue-500 rounded-t-lg" style={{height:`${Math.max(5,day.amount/max*85)}%`}}/><span className="text-[10px] text-gray-400 mt-2">{day.date.slice(8)}</span></div>)}{!report.daily.length&&<p className="m-auto text-gray-400 text-sm">ยังไม่มียอดขายในช่วงนี้</p>}</div></section><section className="bg-white rounded-2xl border border-gray-100 p-5"><h2 className="font-semibold">เมนูขายดี</h2><div className="mt-4 space-y-3">{report.topItems.map((item,index)=><div key={item.name} className="flex items-center gap-3"><span className="w-7 h-7 rounded-lg bg-blue-50 text-blue-600 grid place-items-center text-xs">{index+1}</span><div className="flex-1"><p className="text-sm font-medium">{item.name}</p><p className="text-xs text-gray-400">{item.qty} รายการ</p></div><span className="font-medium">฿{item.sales.toFixed(2)}</span></div>)}{!report.topItems.length&&<p className="text-gray-400 text-sm">ยังไม่มีข้อมูล</p>}</div></section></div>
  <section className="bg-white rounded-2xl border border-gray-100 overflow-x-auto"><div className="p-5 flex justify-between"><h2 className="font-semibold">ประวัติการชำระเงิน</h2><div className="flex gap-3 text-xs text-gray-500">{report.payments.map(p=><span key={p.method}>{methodText[p.method]} ฿{p.amount.toFixed(2)}</span>)}</div></div><table className="w-full text-sm"><thead className="bg-gray-50 text-gray-500"><tr><th className="p-3 text-left">เลขออเดอร์</th><th className="p-3 text-left">โต๊ะ</th><th className="p-3 text-left">เวลา</th><th className="p-3 text-left">ช่องทาง</th><th className="p-3 text-right">ยอดรวม</th></tr></thead><tbody>{report.recent.map(row=><tr key={row.id} className="border-t border-gray-100"><td className="p-3">{row.orderNumber}</td><td className="p-3">{row.table}</td><td className="p-3 text-gray-500">{new Date(row.paidAt).toLocaleString("th-TH")}</td><td className="p-3">{methodText[row.method]||row.method}</td><td className="p-3 text-right font-medium">฿{row.total.toFixed(2)}</td></tr>)}</tbody></table>{!report.recent.length&&<p className="text-center py-8 text-gray-400">ยังไม่มีประวัติการชำระเงิน</p>}</section></div>;
}
