import { CalendarDays, Filter, Search, X } from "lucide-react";
import { auditGroups } from "@/lib/audit-groups";
import type { RangeMode } from "../types";

export const allActionsValue = "__ALL__";

export default function AuditFilters({ title, description, query, action, rangeMode, visibleFrom, visibleTo, fromDisabled, hasFilters, onQuery, onAction, onRange, onFrom, onTo, onClear }: { title: string; description: string; query: string; action: string; rangeMode: RangeMode; visibleFrom: string; visibleTo: string; fromDisabled: boolean; hasFilters: boolean; onQuery: (value: string) => void; onAction: (value: string) => void; onRange: (value: RangeMode) => void; onFrom: (value: string) => void; onTo: (value: string) => void; onClear: () => void }) {
  const options: Array<{ value: RangeMode; label: string }> = [
    { value: "ALL", label: "ทั้งหมด" }, { value: "TODAY", label: "วันนี้" }, { value: "7D", label: "7 วันล่าสุด" }, { value: "MONTH", label: "เดือนนี้" }, { value: "CUSTOM", label: "กำหนดเอง" },
  ];

  return <section className="rounded-2xl border border-gray-100 bg-white p-5"><div><h2 className="font-semibold text-gray-900">{title}</h2><p className="mt-1 text-sm text-gray-400">{description}</p></div><div className="mt-5 flex flex-col gap-3 lg:flex-row"><label className="relative min-w-0 flex-1"><span className="sr-only">ค้นหา</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={17} /><input value={query} maxLength={100} onChange={event => onQuery(event.target.value)} placeholder="ค้นหาชื่อพนักงาน เลขออเดอร์ หรือรายละเอียด" className="w-full rounded-xl border border-gray-200 py-3 pl-10 pr-3 text-sm outline-none focus:border-blue-400" /></label><label className="relative lg:w-64"><span className="sr-only">ประเภทกิจกรรม</span><Filter className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} /><select value={action} onChange={event => onAction(event.target.value)} className="w-full appearance-none rounded-xl border border-gray-200 bg-white py-3 pl-10 pr-8 text-sm outline-none focus:border-blue-400"><option value="">กิจกรรมสำคัญ</option><option value={allActionsValue}>ทั้งหมด</option>{auditGroups.map(group => <option key={group.id} value={group.id}>{group.label}</option>)}</select></label></div><div className="mt-3 flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between"><div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-end"><label className="sm:w-56"><span className="mb-1 block text-xs text-gray-400">แสดง</span><div className="relative"><CalendarDays className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={16} /><select value={rangeMode} onChange={event => onRange(event.target.value as RangeMode)} className="w-full appearance-none rounded-xl border border-gray-200 bg-white py-3 pl-10 pr-8 text-sm outline-none focus:border-blue-400">{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div></label><label className="sm:w-44"><span className="mb-1 block text-xs text-gray-400">จาก</span><input type="date" value={visibleFrom} disabled={fromDisabled} onChange={event => onFrom(event.target.value)} className="w-full rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-blue-400 disabled:bg-gray-50 disabled:text-gray-400" /></label><label className="sm:w-44"><span className="mb-1 block text-xs text-gray-400">ถึง</span><input type="date" value={visibleTo} onChange={event => onTo(event.target.value)} className="w-full rounded-xl border border-gray-200 px-3 py-3 text-sm outline-none focus:border-blue-400" /></label></div>{hasFilters && <button type="button" onClick={onClear} className="inline-flex w-fit items-center gap-1.5 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm text-gray-600"><X size={15} />ล้างตัวกรอง</button>}</div></section>;
}
