"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Armchair, Plus } from "lucide-react";

type ActiveOrder={id:number;orderNumber:string;total:number;status:string};
type Table={id:number;name:string;seats:number;status:string;orders:ActiveOrder[]};
const statusText:Record<string,string>={AVAILABLE:"ว่าง",OCCUPIED:"กำลังใช้งาน",RESERVED:"จอง",CLEANING:"รอทำความสะอาด"};
const statusClass:Record<string,string>={AVAILABLE:"bg-emerald-100 text-emerald-700",OCCUPIED:"bg-red-100 text-red-700",RESERVED:"bg-amber-100 text-amber-700",CLEANING:"bg-gray-100 text-gray-600"};
const orderStatusText:Record<string,string>={SENT:"ส่งครัวแล้ว",PREPARING:"กำลังทำ",READY:"พร้อมเสิร์ฟ",SERVED:"เสิร์ฟแล้ว"};

export default function TablesPage(){
  const [tables,setTables]=useState<Table[]>([]);const [name,setName]=useState("");const [seats,setSeats]=useState("2");const [message,setMessage]=useState("");
  const load=useCallback(()=>fetch("/api/tables").then(r=>r.json()).then(setTables),[]);useEffect(()=>{load();},[load]);
  async function add(e:FormEvent){e.preventDefault();const r=await fetch("/api/tables",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,seats})});const d=await r.json();if(!r.ok)return setMessage(d.error);setName("");load();}
  async function status(id:number,status:string){await fetch("/api/tables",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});load();}
  async function pay(orderId:number,method:string){if(!confirm("ยืนยันรับชำระเงินออเดอร์นี้?"))return;const r=await fetch("/api/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"pay",orderId,method})});const d=await r.json();if(!r.ok)return setMessage(d.error);setMessage("ชำระเงินและคืนสถานะโต๊ะว่างแล้ว");load();}
  async function cancel(orderId:number){if(!confirm("ยืนยันยกเลิกออเดอร์? วัตถุดิบจะถูกคืนเข้าสต็อก"))return;const r=await fetch("/api/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"cancel",orderId})});const d=await r.json();if(!r.ok)return setMessage(d.error);setMessage("ยกเลิกออเดอร์และคืนสต็อกแล้ว");load();}
  return <div className="p-6"><form onSubmit={add} className="bg-white rounded-2xl p-4 flex flex-col sm:flex-row gap-3"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="ชื่อโต๊ะ เช่น A1" className="flex-1 border rounded-xl px-4 py-2"/><input required type="number" min="1" value={seats} onChange={e=>setSeats(e.target.value)} className="sm:w-32 border rounded-xl px-4 py-2"/><button className="bg-[#356DDB] text-white rounded-xl px-5 py-2 flex items-center justify-center gap-2"><Plus size={17}/> เพิ่มโต๊ะ</button></form>{message&&<p className="mt-3 text-sm text-blue-600">{message}</p>}
  <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 mt-5">{tables.map(table=>{const order=table.orders[0];return <div key={table.id} className="bg-white rounded-2xl p-5 border border-gray-100"><div className="flex justify-between"><div className="w-11 h-11 rounded-xl bg-blue-50 text-blue-600 grid place-items-center"><Armchair size={22}/></div><span className={`h-fit px-3 py-1 rounded-full text-xs ${statusClass[table.status]}`}>{statusText[table.status]}</span></div><h3 className="text-xl font-semibold mt-4">{table.name}</h3><p className="text-sm text-gray-400">{table.seats} ที่นั่ง</p>{order?<div className="mt-4 bg-gray-50 rounded-xl p-3"><p className="text-xs text-gray-400">{order.orderNumber}</p><div className="flex justify-between font-medium mt-1"><span>{orderStatusText[order.status]||order.status}</span><span>฿{order.total.toFixed(2)}</span></div><div className="grid grid-cols-3 gap-1 mt-3"><button onClick={()=>pay(order.id,"CASH")} className="bg-emerald-600 text-white rounded-lg py-1.5 text-xs">เงินสด</button><button onClick={()=>pay(order.id,"PROMPTPAY")} className="bg-blue-600 text-white rounded-lg py-1.5 text-xs">พร้อมเพย์</button><button onClick={()=>pay(order.id,"CARD")} className="bg-gray-700 text-white rounded-lg py-1.5 text-xs">บัตร</button></div><button onClick={()=>cancel(order.id)} className="mt-2 w-full bg-red-50 text-red-600 rounded-lg py-1.5 text-xs">ยกเลิกออเดอร์</button></div>:<div className="flex gap-2 mt-4"><button onClick={()=>status(table.id,table.status==="RESERVED"?"AVAILABLE":"RESERVED")} className="flex-1 bg-amber-50 text-amber-700 rounded-lg py-2 text-xs">{table.status==="RESERVED"?"ยกเลิกจอง":"จองโต๊ะ"}</button><button onClick={()=>status(table.id,table.status==="CLEANING"?"AVAILABLE":"CLEANING")} className="flex-1 bg-gray-100 text-gray-600 rounded-lg py-2 text-xs">{table.status==="CLEANING"?"ทำความสะอาดแล้ว":"รอทำความสะอาด"}</button></div>}</div>})}</div>{!tables.length&&<p className="text-center text-gray-400 mt-12">เพิ่มโต๊ะเพื่อเริ่มรับออเดอร์</p>}</div>;
}
