/** Integration test against a running local app. Creates and removes its own restaurant. */
import 'dotenv/config';
import assert from 'node:assert/strict';
import { randomBytes, createHash } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
const db = new PrismaClient();
const base = process.env.QR_TEST_BASE_URL || 'http://localhost:3000';
let restaurant;
let foreignRestaurant;
let cookie;
const id = () => randomBytes(20).toString('hex');
async function call(path, body, staff = false, method = 'POST') {
  const response = await fetch(base + path, { method: body ? method : 'GET', headers: { 'Content-Type': 'application/json', ...(staff ? { cookie } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
  return { status: response.status, data: await response.json() };
}
try {
  restaurant = await db.restaurant.create({ data: { name: 'QR Integration Test', slug: `qr-test-${id()}` } });
  const rid = restaurant.id;
  const employee = await db.employee.create({ data: { restaurantId: rid, username: `qr-test-${id()}`, displayName: 'QR Test', passwordHash: 'unused', roles: { create: { role: 'OWNER' } } } });
  const token = id();
  await db.authSession.create({ data: { employeeId: employee.id, tokenHash: createHash('sha256').update(token).digest('hex'), expiresAt: new Date(Date.now() + 3600000) } });
  cookie = `restaurant_session=${token}`;
  const category = await db.category.create({ data: { restaurantId: rid, name: 'Food' } });
  const ingredient = await db.ingredient.create({ data: { restaurantId: rid, name: 'Rice', unit: 'portion', stock: 20 } });
  const menu = await db.menuItem.create({ data: { restaurantId: rid, categoryId: category.id, name: 'Rice dish', sku: 'TEST', price: 65, recipes: { create: { ingredientId: ingredient.id, quantity: 1 } } } });
  const table = await db.restaurantTable.create({ data: { restaurantId: rid, name: 'Test table' } });
  const session = action => call('/api/table-sessions', { tableId: table.id, action }, true);
  assert.equal((await call('/api/table-sessions', { tableId: table.id, action: 'open' })).status, 401);
  const opened = await session('open'); assert.equal(opened.status, 200, JSON.stringify(opened));
  let qr = opened.data.url.split('/').at(-1);
  assert.equal((await session('open')).data.url, opened.data.url);
  assert.match(opened.data.qr, /^data:image\/png;base64,/);
  const guestA = id(), guestB = id();
  const submit = (guestId, requestId = id(), qty = 1, menuItemId = menu.id) => call(`/api/guest/${qr}`, { guestId, requestId, items: [{ menuItemId, qty }] });
  const reqId = id();
  const concurrent = await Promise.all([submit(guestA, reqId), submit(guestA, reqId), submit(guestB)]);
  assert.deepEqual(concurrent.map(r => r.status), [201, 201, 201], JSON.stringify(concurrent));
  let order = await db.order.findFirst({ where: { restaurantId: rid }, include: { items: true } });
  assert.equal(await db.order.count({ where: { restaurantId: rid } }), 1);
  assert.equal(order.items.length, 2); assert.equal(order.total, 130);
  assert.equal((await db.ingredient.findUnique({ where: { id: ingredient.id } })).stock, 18);
  const guestView = await call(`/api/guest/${qr}?guestId=${guestA}`);
  assert.equal(guestView.data.order.items.filter(i => i.mine).length, 1);
  assert.ok(!JSON.stringify(guestView.data).includes('costPerUnit'));
  assert.ok(!('guestId' in guestView.data.order.items[0]));
  assert.equal((await submit(guestA)).status, 429);
  assert.equal((await submit(id(), id(), 0)).status, 400);
  assert.equal((await submit(id(), id(), 1, 2147483647)).status, 400);
  assert.equal((await submit(id(), id(), 50)).status, 409);
  assert.equal((await db.order.findUnique({ where: { id: order.id } })).total, 130);
  await session('pause'); assert.equal((await submit(id())).status, 429);
  await session('resume'); assert.equal((await submit(id())).status, 201);
  const oldQr = qr;
  qr = (await session('rotate')).data.url.split('/').at(-1);
  assert.notEqual(qr, oldQr);
  assert.equal((await call(`/api/guest/${oldQr}`)).status, 410);
  assert.equal((await call(`/api/guest/${oldQr}`, { guestId: guestA, requestId: id(), items: [{ menuItemId: menu.id, qty: 1 }] })).status, 410);
  assert.equal((await call(`/api/guest/${qr}`, { action: 'bill' })).status, 200);
  assert.equal((await submit(id())).status, 429);
  const tables = await call('/api/tables', null, true);
  assert.ok(tables.data.find(t => t.id === table.id).sessions[0].billRequestedAt);
  await session('clear-bill');
  // Staff and guest additions share a bill and cannot create a second active order.
  const mixed = await Promise.all([submit(id()), call('/api/orders', { tableId: table.id, items: [{ menuItemId: menu.id, qty: 1 }] }, true)]);
  assert.deepEqual(mixed.map(r => r.status), [201, 201]);
  order = await db.order.findUnique({ where: { id: order.id }, include: { items: true } });
  assert.equal(order.total, 325);
  assert.equal(order.items.filter(i => i.source === 'QR').length, 4);
  const pay = await call('/api/orders', { action: 'pay', orderId: order.id, method: 'CASH', receivedAmount: 400 }, true, 'PATCH');
  assert.equal(pay.status, 200, JSON.stringify(pay));
  const paidAudit = await db.auditLog.findFirstOrThrow({ where: { restaurantId: rid, action: 'PAY_ORDER', entityId: String(order.id) } });
  assert.equal(paidAudit.employeeId, employee.id);
  assert.equal(paidAudit.details.actorName, 'QR Test');
  assert.equal(paidAudit.details.total, 325);
  assert.equal(paidAudit.details.receivedAmount, 400);
  assert.equal(paidAudit.details.changeAmount, 75);
  assert.equal(paidAudit.details.items.reduce((sum, item) => sum + item.qty * item.price, 0), 325);
  const createdAudit = await db.auditLog.findFirstOrThrow({ where: { restaurantId: rid, action: 'CREATE_ORDER', entityId: String(order.id) } });
  assert.equal(createdAudit.details.items.reduce((sum, item) => sum + item.qty, 0), 1);
  assert.equal(createdAudit.details.actorName, 'ลูกค้าผ่าน QR');
  assert.equal((await call('/api/orders', { action: 'pay', orderId: order.id, method: 'CASH', receivedAmount: 400 }, true, 'PATCH')).status, 500);
  assert.equal(await db.auditLog.count({ where: { restaurantId: rid, action: 'PAY_ORDER', entityId: String(order.id) } }), 1);
  assert.equal((await call(`/api/guest/${qr}`)).status, 410);
  assert.equal((await submit(id())).status, 410);
  qr = (await session('open')).data.url.split('/').at(-1);
  assert.equal((await call(`/api/guest/${qr}`)).data.order, null);
  await session('close'); assert.equal((await call(`/api/guest/${qr}`)).status, 410);
  // Race two guests for the last portion: exactly one succeeds, no negative stock.
  qr = (await session('open')).data.url.split('/').at(-1);
  await db.ingredient.update({ where: { id: ingredient.id }, data: { stock: 1 } });
  const lastPortion = await Promise.all([submit(id()), submit(id())]);
  assert.deepEqual(lastPortion.map(r => r.status).sort(), [201, 409], JSON.stringify(lastPortion));
  assert.equal((await db.ingredient.findUnique({ where: { id: ingredient.id } })).stock, 0);
  order = await db.order.findFirst({ where: { restaurantId: rid, paymentStatus: 'UNPAID', status: { not: 'CANCELLED' } } });
  const cancelled = await call('/api/orders', { action: 'cancel', orderId: order.id }, true, 'PATCH');
  assert.equal(cancelled.status, 200);
  assert.equal((await call(`/api/guest/${qr}`)).status, 410);
  qr = (await session('open')).data.url.split('/').at(-1);
  await db.ingredient.update({ where: { id: ingredient.id }, data: { stock: 10 } });
  assert.equal((await submit(id())).status, 201);
  order = await db.order.findFirst({ where: { restaurantId: rid, paymentStatus: 'UNPAID', status: { not: 'CANCELLED' } } });
  const paymentRace = await Promise.all([submit(id()), call('/api/orders', { action: 'pay', orderId: order.id, method: 'CASH', receivedAmount: 1000 }, true, 'PATCH')]);
  assert.ok([201, 410].includes(paymentRace[0].status), JSON.stringify(paymentRace));
  assert.equal(paymentRace[1].status, 200, JSON.stringify(paymentRace));
  const settled = await db.order.findUnique({ where: { id: order.id }, include: { payment: true } });
  assert.equal(settled.payment.amount, settled.total);
  assert.equal(await db.order.count({ where: { restaurantId: rid, paymentStatus: 'UNPAID', status: { not: 'CANCELLED' } } }), 0);
  assert.equal((await submit(id())).status, 410);
  // Tenant boundaries and required options are enforced by the public endpoint too.
  foreignRestaurant = await db.restaurant.create({ data: { name: 'QR Integration Test', slug: `qr-test-${id()}` } });
  const foreignCategory = await db.category.create({ data: { restaurantId: foreignRestaurant.id, name: 'Other' } });
  const foreignMenu = await db.menuItem.create({ data: { restaurantId: foreignRestaurant.id, categoryId: foreignCategory.id, name: 'Other menu', sku: 'OTHER', price: 1 } });
  const foreignTable = await db.restaurantTable.create({ data: { restaurantId: foreignRestaurant.id, name: 'Other table' } });
  assert.equal((await call('/api/table-sessions', { tableId: foreignTable.id, action: 'open' }, true)).status, 404);
  qr = (await session('open')).data.url.split('/').at(-1);
  assert.equal((await submit(id(), id(), 1, foreignMenu.id)).status, 400);
  const group = await db.menuItemModifierGroup.create({ data: { restaurantId: rid, menuItemId: menu.id, name: 'Required topping', required: true, minSelect: 1, maxSelect: 1 } });
  const topping = await db.ingredient.create({ data: { restaurantId: rid, name: 'Egg', unit: 'piece', stock: 1 } });
  const option = await db.menuItemModifier.create({ data: { restaurantId: rid, menuItemId: menu.id, groupId: group.id, name: 'Egg', price: 10, recipes: { create: { ingredientId: topping.id, quantity: 1 } } } });
  assert.equal((await submit(id())).status, 409);
  const withOption = qty => call(`/api/guest/${qr}`, { guestId: id(), requestId: id(), items: [{ menuItemId: menu.id, qty, modifierIds: [option.id] }] });
  assert.equal((await withOption(2)).status, 409);
  assert.equal((await withOption(1)).status, 201);
  order = await db.order.findFirst({ where: { restaurantId: rid, paymentStatus: 'UNPAID', status: { not: 'CANCELLED' } } });
  assert.equal(order.total, 75);
  assert.equal((await db.ingredient.findUnique({ where: { id: topping.id } })).stock, 0);
  assert.equal((await call('/api/orders', { action: 'cancel', orderId: order.id }, true, 'PATCH')).status, 200);
  const newRound = await session('open');
  assert.equal((await call('/api/orders', { action: 'cancel', orderId: order.id }, true, 'PATCH')).status, 500);
  assert.equal((await call('/api/orders', { action: 'pay', orderId: order.id, method: 'CASH', receivedAmount: 100 }, true, 'PATCH')).status, 500);
  assert.equal((await call(`/api/guest/${newRound.data.url.split('/').at(-1)}`)).status, 200);
  console.log('PASS: authentication, QR reuse/rotation/closure, concurrent devices, idempotency, ownership view, validation, stock rollback/race, pause/resume, bill request, staff/guest shared bill, payment and cancellation.');
} finally {
  const cleanupRestaurants = [restaurant, foreignRestaurant].filter(Boolean);
  for (const restaurant of cleanupRestaurants) {
    await db.menuItemModifierRecipe.deleteMany({ where: { modifier: { restaurantId: restaurant.id } } });
    await db.recipe.deleteMany({ where: { menuItem: { restaurantId: restaurant.id } } });
    await db.order.deleteMany({ where: { restaurantId: restaurant.id } });
    await db.menuItem.deleteMany({ where: { restaurantId: restaurant.id } });
    await db.restaurant.delete({ where: { id: restaurant.id } });
  }
  await db.$disconnect();
}
